# Generated by Django 4.1.7 on 2023-03-07 17:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0003_publication_comments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publication",
            name="comments",
        ),
    ]
