# Generated by Django 4.1.7 on 2023-03-07 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("publications", "0004_remove_publication_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="comments",
            field=models.ManyToManyField(
                related_name="comment",
                through="publications.Comment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
