# Generated by Django 4.1.7 on 2023-03-12 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("publications", "0006_publication_acess_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="likes",
            field=models.ManyToManyField(
                related_name="like",
                through="publications.Like",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
